services:
  telegram-dumper:
    build:
      context: telegram-dumper/
    environment:
      TELEGRAM_API_ID:
      TELEGRAM_API_HASH:
    volumes:
      - ./telegram-dumper/Pipfile:/var/app/Pipfile
      - ./telegram-dumper/Pipfile.lock:/var/app/Pipfile.lock
      - ./telegram-dumper/src/:/var/app/src/
      - ./telegram-dumper/sessions/:/var/app/sessions/
      - ./data/:/var/app/data/
  stt:
    build:
      context: stt/
    volumes:
      - ./stt/Pipfile:/var/app/Pipfile
      - ./stt/Pipfile.lock:/var/app/Pipfile.lock
      - ./stt/src/:/var/app/src/
      - ./huggingface/:/root/.cache/huggingface/
      - ./data/:/var/app/data/
